### ISSUE TITLE
server-side rending warning

### ISSUE THREAD

**Issue by chihsuan** [react-d3/react-d3-map-core#14]
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ore__container_svg__90954" data-reactid=
 (server) ore__container_svg__56547" data-reactid=

A server side rendering warning, which  is probably cause by `react-d3-map-core svg.jsx`: 
https://github.com/react-d3/react-d3-core/blob/master/src/container/svg.jsx#L32, so  client data-reactid is always different.

**Comment by chilijung** [comment]
try react-d3-map@0.4.3
